import { Recruitment } from '~/types/recruitment';

export const RECRUITMENTS = [
  {
    id: 1,
    company_name: '회사명1',
    title: '공고 제목1',
    badge: ['국내 거주 필수'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '회사명1 공고 제목1',
    like: false,
    occupation: '경영・비즈니스',
    region: '국내 거주 필수',
    employment_type: '정규직',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 2,
    company_name: '회사명2',
    title: '공고 제목2',
    badge: ['국내 거주 필수', '부분원격근무', '주 40시간(풀타임)'],
    country: '영국',
    image_url: 'https://picsum.photos/200',
    contents: '회사명2 공고 제목2',
    like: true,
    occupation: '금융',
    region: '지역 제한 없음',
    employment_type: '계약직',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 3,
    company_name: '회사명3',
    title: '공고 제목3',
    badge: ['국내 거주 필수', '정규직', '주 40시간(풀타임)'],
    country: '미국',
    image_url: 'https://picsum.photos/200',
    contents: '회사명3 공고 제목3',
    like: false,
    occupation: 'HR',
    region: '국내 거주 필수',
    employment_type: '프리랜서',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 4,
    company_name: '회사명4',
    title: '공고 제목4',
    badge: ['부분원격근무', '정규직', '주 40시간(풀타임)'],
    country: '아일랜드',
    image_url: 'https://picsum.photos/200',
    contents: '회사명4 공고 제목4',
    like: true,
    occupation: 'HR',
    region: '국내 거주 필수',
    employment_type: '정규직',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 5,
    company_name: '회사명5',
    title: '공고 제목5',
    badge: ['정규직', '주 40시간(풀타임)'],
    country: '프랑스',
    image_url: 'https://picsum.photos/200',
    contents: '회사명5 공고 제목5',
    like: false,
    occupation: 'HR',
    region: '국내 거주 필수',
    employment_type: '정규직',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 6,
    company_name: '회사명6',
    title: '공고 제목6',
    badge: ['국내 거주 필수', '부분원격근무', '정규직'],
    country: '뉴질랜드',
    image_url: 'https://picsum.photos/200',
    contents: '회사명6 공고 제목6',
    like: true,
    occupation: 'HR',
    region: '국내 거주 필수',
    employment_type: '계약직',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 7,
    company_name: '회사명7',
    title: '공고 제목7',
    badge: ['국내 거주 필수', '정규직', '주 40시간(풀타임)'],
    country: '스위스',
    image_url: 'https://picsum.photos/200',
    contents: '회사명7 공고 제목7',
    like: false,
    occupation: 'HR',
    region: '국내 거주 필수',
    employment_type: '정규직',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 8,
    company_name: '회사명8',
    title: '공고 제목8',
    badge: ['국내 거주 필수', '부분원격근무', '정규직'],
    country: '오스트리아',
    image_url: 'https://picsum.photos/200',
    contents: '회사명8 공고 제목8',
    like: true,
    occupation: '기타',
    region: '국내 거주 필수',
    employment_type: '프리랜서',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 9,
    company_name: '회사명9',
    title: '공고 제목9',
    badge: ['국내 거주 필수', '유연근무', '정규직', '주 40시간(풀타임)'],
    country: '호주',
    image_url: 'https://picsum.photos/200',
    contents: '회사명9 공고 제목9',
    like: false,
    occupation: 'HR',
    region: '국내 거주 필수',
    employment_type: '정규직',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 10,
    company_name: '회사명10',
    title: '공고 제목10',
    badge: ['국내 거주 필수', '부분원격근무', '정규직', '주 40시간(풀타임)'],
    country: '일본',
    image_url: 'https://picsum.photos/200',
    contents: '회사명10 공고 제목10',
    like: true,
    occupation: 'HR',
    region: '국내 거주 필수',
    employment_type: '계약직',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 11,
    company_name: '회사명11',
    title: '공고 제목11',
    badge: ['국내 거주 필수'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '회사명11 공고 제목11',
    like: false,
    occupation: '경영・비즈니스',
    region: '국내 거주 필수',
    employment_type: '정규직',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 12,
    company_name: '회사명12',
    title: '공고 제목12',
    badge: ['국내 거주 필수', '부분원격근무', '주 40시간(풀타임)'],
    country: '영국',
    image_url: 'https://picsum.photos/200',
    contents: '회사명12 공고 제목12',
    like: true,
    occupation: '금융',
    region: '지역 제한 없음',
    employment_type: '계약직',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 13,
    company_name: '회사명13',
    title: '공고 제목13',
    badge: ['국내 거주 필수', '정규직', '주 40시간(풀타임)'],
    country: '미국',
    image_url: 'https://picsum.photos/200',
    contents: '회사명13 공고 제목13',
    like: false,
    occupation: 'HR',
    region: '국내 거주 필수',
    employment_type: '프리랜서',
    career: '경력무관',
    working_hours_per_week: '주 20-30시간 미만',
  },
  {
    id: 14,
    company_name: '테크스타트업',
    title: '시니어 프론트엔드 개발자 (React)',
    badge: ['100% 원격근무', '정규직', '주 40시간(풀타임)'],
    country: '싱가포르',
    image_url: 'https://picsum.photos/200',
    contents: '글로벌 테크 스타트업에서 시니어 프론트엔드 개발자를 모십니다',
    like: false,
    occupation: '테크',
    region: '지역 제한 없음',
    employment_type: '정규직',
    career: '경력 5년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 15,
    company_name: '글로벌커머스',
    title: '데이터 분석가 (신입 가능)',
    badge: ['유연근무', '정규직'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '글로벌 이커머스 기업의 데이터 분석가를 모집합니다',
    like: true,
    occupation: '데이터',
    region: '서울',
    employment_type: '정규직',
    career: '경력무관',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 16,
    company_name: '핀테크솔루션',
    title: '백엔드 개발자 (Python/Django)',
    badge: ['부분원격근무', '정규직', '주 40시간(풀타임)'],
    country: '독일',
    image_url: 'https://picsum.photos/200',
    contents: '유럽 진출을 앞둔 핀테크 기업의 백엔드 개발자를 찾습니다',
    like: false,
    occupation: '테크',
    region: '지역 제한 없음',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 17,
    company_name: '에듀테크코리아',
    title: '프로덕트 매니저 (PM)',
    badge: ['국내 거주 필수', '정규직'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '급성장하는 에듀테크 기업의 프로덕트 매니저를 모십니다',
    like: true,
    occupation: '기획・PM',
    region: '서울',
    employment_type: '정규직',
    career: '경력 2년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 18,
    company_name: '메디컬AI',
    title: 'AI 리서치 엔지니어',
    badge: ['100% 원격근무', '정규직', '주 40시간(풀타임)'],
    country: '캐나다',
    image_url: 'https://picsum.photos/200',
    contents: '의료 AI 솔루션 개발을 위한 리서치 엔지니어를 모집합니다',
    like: false,
    occupation: 'AI・머신러닝',
    region: '지역 제한 없음',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 19,
    company_name: '글로벌마케팅그룹',
    title: '디지털 마케팅 매니저',
    badge: ['유연근무', '정규직'],
    country: '홍콩',
    image_url: 'https://picsum.photos/200',
    contents: '아시아 시장을 선도하는 마케팅 그룹의 디지털 마케터를 찾습니다',
    like: true,
    occupation: '마케팅・광고',
    region: '아시아',
    employment_type: '정규직',
    career: '경력 4년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 20,
    company_name: '클라우드서비스',
    title: 'DevOps 엔지니어',
    badge: ['부분원격근무', '정규직', '주 40시간(풀타임)'],
    country: '스웨덴',
    image_url: 'https://picsum.photos/200',
    contents: '글로벌 클라우드 서비스 기업의 DevOps 엔지니어를 모집합니다',
    like: false,
    occupation: '테크',
    region: '유럽',
    employment_type: '정규직',
    career: '경력 5년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 21,
    company_name: '헬스케어스타트업',
    title: '헬스케어 컨설턴트',
    badge: ['국내 거주 필수', '계약직'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '헬스케어 스타트업에서 컨설턴트를 모집합니다',
    like: true,
    occupation: '컨설팅',
    region: '서울',
    employment_type: '계약직',
    career: '경력 2년 이상',
    working_hours_per_week: '주 30-40시간',
  },
  {
    id: 22,
    company_name: '에너지솔루션',
    title: '에너지 분석가',
    badge: ['100%원격근무', '프리랜서'],
    country: '미국',
    image_url: 'https://picsum.photos/200',
    contents: '에너지 솔루션 기업에서 분석가를 모집합니다',
    like: false,
    occupation: '에너지',
    region: '지역 제한 없음',
    employment_type: '프리랜서',
    career: '경력 1년 이상',
    working_hours_per_week: '주 20-30시간',
  },
  {
    id: 23,
    company_name: '모바일게임사',
    title: '게임 디자이너',
    badge: ['부분원격근무', '정규직'],
    country: '일본',
    image_url: 'https://picsum.photos/200',
    contents: '모바일 게임사에서 게임 디자이너를 모집합니다',
    like: true,
    occupation: '디자인',
    region: '도쿄',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 24,
    company_name: '로봇공학연구소',
    title: '로봇 소프트웨어 엔지니어',
    badge: ['국내 거주 필수', '정규직'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '로봇공학 연구소에서 소프트웨어 엔지니어를 모집합니다',
    like: false,
    occupation: '로봇공학',
    region: '대전',
    employment_type: '정규직',
    career: '경력 4년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 25,
    company_name: '블록체인스타트업',
    title: '블록체인 개발자',
    badge: ['100%원격근무', '정규직'],
    country: '스위스',
    image_url: 'https://picsum.photos/200',
    contents: '블록체인 스타트업에서 개발자를 모집합니다',
    like: true,
    occupation: '블록체인',
    region: '지역 제한 없음',
    employment_type: '정규직',
    career: '경력 2년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 26,
    company_name: '자동차제조사',
    title: '자동차 엔지니어',
    badge: ['부분원격근무', '계약직'],
    country: '독일',
    image_url: 'https://picsum.photos/200',
    contents: '자동차 제조사에서 엔지니어를 모집합니다',
    like: false,
    occupation: '제조',
    region: '뮌헨',
    employment_type: '계약직',
    career: '경력 5년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 27,
    company_name: '패션브랜드',
    title: '패션 디자이너',
    badge: ['국내 거주 필수', '정규직'],
    country: '프랑스',
    image_url: 'https://picsum.photos/200',
    contents: '글로벌 패션 브랜드에서 디자이너를 모집합니다',
    like: true,
    occupation: '디자인',
    region: '파리',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 28,
    company_name: '우주항공기업',
    title: '항공우주 엔지니어',
    badge: ['100%원격근무', '정규직'],
    country: '미국',
    image_url: 'https://picsum.photos/200',
    contents: '우주항공 기업에서 엔지니어를 모집합니다',
    like: false,
    occupation: '항공우주',
    region: '지역 제한 없음',
    employment_type: '정규직',
    career: '경력 5년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 29,
    company_name: '바이오테크',
    title: '생명공학 연구원',
    badge: ['부분원격근무', '정규직'],
    country: '영국',
    image_url: 'https://picsum.photos/200',
    contents: '바이오테크 기업에서 연구원을 모집합니다',
    like: true,
    occupation: '생명공학',
    region: '런던',
    employment_type: '정규직',
    career: '경력 4년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 30,
    company_name: '스마트홈솔루션',
    title: 'IoT 개발자',
    badge: ['국내 거주 필수', '정규직'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '스마트홈 솔루션 기업에서 IoT 개발자를 모집합니다',
    like: false,
    occupation: 'IoT',
    region: '서울',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 31,
    company_name: '에듀테크스타트업',
    title: '교육 콘텐츠 개발자',
    badge: ['100%원격근무', '계약직'],
    country: '호주',
    image_url: 'https://picsum.photos/200',
    contents: '에듀테크 스타트업에서 콘텐츠 개발자를 모집합니다',
    like: true,
    occupation: '교육',
    region: '시드니',
    employment_type: '계약직',
    career: '경력 2년 이상',
    working_hours_per_week: '주 30-40시간',
  },
  {
    id: 32,
    company_name: '모바일앱개발사',
    title: '모바일 앱 디자이너',
    badge: ['부분원격근무', '정규직'],
    country: '캐나다',
    image_url: 'https://picsum.photos/200',
    contents: '모바일 앱 개발사에서 디자이너를 모집합니다',
    like: false,
    occupation: '디자인',
    region: '토론토',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 33,
    company_name: '헬스케어AI',
    title: 'AI 엔지니어',
    badge: ['국내 거주 필수', '정규직'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '헬스케어 AI 기업에서 엔지니어를 모집합니다',
    like: true,
    occupation: 'AI・머신러닝',
    region: '서울',
    employment_type: '정규직',
    career: '경력 4년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 34,
    company_name: '핀테크스타트업',
    title: '프론트엔드 개발자',
    badge: ['100%원격근무', '계약직'],
    country: '싱가포르',
    image_url: 'https://picsum.photos/200',
    contents: '핀테크 스타트업에서 프론트엔드 개발자를 모집합니다',
    like: false,
    occupation: '테크',
    region: '지역 제한 없음',
    employment_type: '계약직',
    career: '경력 2년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 35,
    company_name: '글로벌컨설팅',
    title: '비즈니스 컨설턴트',
    badge: ['부분원격근무', '정규직'],
    country: '홍콩',
    image_url: 'https://picsum.photos/200',
    contents: '글로벌 컨설팅 기업에서 비즈니스 컨설턴트를 모집합니다',
    like: true,
    occupation: '컨설팅',
    region: '아시아',
    employment_type: '정규직',
    career: '경력 5년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 36,
    company_name: '에너지스타트업',
    title: '에너지 솔루션 엔지니어',
    badge: ['국내 거주 필수', '정규직'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '에너지 스타트업에서 솔루션 엔지니어를 모집합니다',
    like: false,
    occupation: '에너지',
    region: '서울',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 37,
    company_name: '모바일게임기업',
    title: '게임 아티스트',
    badge: ['100%원격근무', '정규직'],
    country: '일본',
    image_url: 'https://picsum.photos/200',
    contents: '모바일 게임 기업에서 아티스트를 모집합니다',
    like: true,
    occupation: '디자인',
    region: '도쿄',
    employment_type: '정규직',
    career: '경력 4년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 38,
    company_name: '로봇공학기업',
    title: '로봇 하드웨어 엔지니어',
    badge: ['부분원격근무', '계약직'],
    country: '독일',
    image_url: 'https://picsum.photos/200',
    contents: '로봇공학 기업에서 하드웨어 엔지니어를 모집합니다',
    like: false,
    occupation: '로봇공학',
    region: '뮌헨',
    employment_type: '계약직',
    career: '경력 5년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 39,
    company_name: '패션스타트업',
    title: '패션 마케팅 매니저',
    badge: ['국내 거주 필수', '정규직'],
    country: '프랑스',
    image_url: 'https://picsum.photos/200',
    contents: '패션 스타트업에서 마케팅 매니저를 모집합니다',
    like: true,
    occupation: '마케팅・광고',
    region: '파리',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 40,
    company_name: '우주항공기업',
    title: '항공우주 연구개발 엔지니어',
    badge: ['100%원격근무', '정규직'],
    country: '미국',
    image_url: 'https://picsum.photos/200',
    contents: '우주항공 기업에서 연구개발 엔지니어를 모집합니다',
    like: false,
    occupation: '항공우주',
    region: '지역 제한 없음',
    employment_type: '정규직',
    career: '경력 5년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 41,
    company_name: '바이오기업',
    title: '생명공학 연구원',
    badge: ['부분원격근무', '정규직'],
    country: '영국',
    image_url: 'https://picsum.photos/200',
    contents: '바이오 기업에서 연구원을 모집합니다',
    like: true,
    occupation: '생명공학',
    region: '런던',
    employment_type: '정규직',
    career: '경력 4년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 42,
    company_name: '스마트홈기업',
    title: 'IoT 시스템 엔지니어',
    badge: ['국내 거주 필수', '정규직'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '스마트홈 기업에서 시스템 엔지니어를 모집합니다',
    like: false,
    occupation: 'IoT',
    region: '서울',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 43,
    company_name: '에듀테크스타트업',
    title: '교육 콘텐츠 매니저',
    badge: ['100%원격근무', '계약직'],
    country: '호주',
    image_url: 'https://picsum.photos/200',
    contents: '에듀테크 스타트업에서 콘텐츠 매니저를 모집합니다',
    like: true,
    occupation: '교육',
    region: '시드니',
    employment_type: '계약직',
    career: '경력 2년 이상',
    working_hours_per_week: '주 30-40시간',
  },
  {
    id: 44,
    company_name: '모바일앱기업',
    title: '모바일 앱 개발자',
    badge: ['부분원격근무', '정규직'],
    country: '캐나다',
    image_url: 'https://picsum.photos/200',
    contents: '모바일 앱 기업에서 개발자를 모집합니다',
    like: false,
    occupation: '테크',
    region: '토론토',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 45,
    company_name: '헬스케어기업',
    title: '헬스케어 솔루션 개발자',
    badge: ['국내 거주 필수', '정규직'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '헬스케어 기업에서 솔루션 개발자를 모집합니다',
    like: true,
    occupation: '테크',
    region: '서울',
    employment_type: '정규직',
    career: '경력 4년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 46,
    company_name: '핀테크스타트업',
    title: '데이터 엔지니어',
    badge: ['100%원격근무', '계약직'],
    country: '싱가포르',
    image_url: 'https://picsum.photos/200',
    contents: '핀테크 스타트업에서 데이터 엔지니어를 모집합니다',
    like: false,
    occupation: '데이터',
    region: '지역 제한 없음',
    employment_type: '계약직',
    career: '경력 2년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 47,
    company_name: '글로벌컨설팅기업',
    title: 'IT 컨설턴트',
    badge: ['부분원격근무', '정규직'],
    country: '홍콩',
    image_url: 'https://picsum.photos/200',
    contents: '글로벌 컨설팅 기업에서 IT 컨설턴트를 모집합니다',
    like: true,
    occupation: '컨설팅',
    region: '아시아',
    employment_type: '정규직',
    career: '경력 5년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 48,
    company_name: '에너지스타트업',
    title: '에너지 데이터 분석가',
    badge: ['국내 거주 필수', '정규직'],
    country: '대한민국',
    image_url: 'https://picsum.photos/200',
    contents: '에너지 스타트업에서 데이터 분석가를 모집합니다',
    like: false,
    occupation: '에너지',
    region: '서울',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 49,
    company_name: '모바일게임기업',
    title: '게임 프로듀서',
    badge: ['100%원격근무', '정규직'],
    country: '일본',
    image_url: 'https://picsum.photos/200',
    contents: '모바일 게임 기업에서 프로듀서를 모집합니다',
    like: true,
    occupation: '기획・PM',
    region: '도쿄',
    employment_type: '정규직',
    career: '경력 4년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 50,
    company_name: '로봇공학기업',
    title: '로봇 소프트웨어 개발자',
    badge: ['부분원격근무', '계약직'],
    country: '독일',
    image_url: 'https://picsum.photos/200',
    contents: '로봇공학 기업에서 소프트웨어 개발자를 모집합니다',
    like: false,
    occupation: '로봇공학',
    region: '뮌헨',
    employment_type: '계약직',
    career: '경력 5년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 51,
    company_name: '패션기업',
    title: '패션 마케팅 매니저',
    badge: ['국내 거주 필수', '정규직'],
    country: '프랑스',
    image_url: 'https://picsum.photos/200',
    contents: '패션 기업에서 마케팅 매니저를 모집합니다',
    like: true,
    occupation: '마케팅・광고',
    region: '파리',
    employment_type: '정규직',
    career: '경력 3년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 52,
    company_name: '우주항공스타트업',
    title: '항공우주 시스템 엔지니어',
    badge: ['100%원격근무', '정규직'],
    country: '미국',
    image_url: 'https://picsum.photos/200',
    contents: '우주항공 스타트업에서 시스템 엔지니어를 모집합니다',
    like: false,
    occupation: '항공우주',
    region: '지역 제한 없음',
    employment_type: '정규직',
    career: '경력 5년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
  {
    id: 53,
    company_name: '바이오기업',
    title: '생명공학 연구원',
    badge: ['부분원격근무', '정규직'],
    country: '영국',
    image_url: 'https://picsum.photos/200',
    contents: '바이오 기업에서 연구원을 모집합니다',
    like: true,
    occupation: '생명공학',
    region: '런던',
    employment_type: '정규직',
    career: '경력 4년 이상',
    working_hours_per_week: '주 40시간(풀타임)',
  },
] as Recruitment[];
